### ISSUE TITLE
saliency maps

### ISSUE THREAD

**Issue by sdws1983** [NAMlab/DeepCRE#2]
Hello,

I have a question regarding the saliency maps in your paper: [Figure 3](https://www.nature.com/articles/s41467-024-47744-0/figures/3). Could you clarify what the dark and light lines in the plot represent?

I have successfully followed your code to train the model and make predictions, and I now have an .h5 file containing contrib_scores, hypothetical_scores, and one_hots. How should I analyze these results to reproduce this specific figure?

Thank you for your help!

**Comment by PelFritz** [comment]
Hi @sdws1983 thank you for your question. The dotted lines mark the transcription start sites (TSS) and transcription termination sites (TTS). In our work we considered the start of the gene to be the TSS and end of the gene to be the TTS. To get a similar plot, you have to average the contribution scores across all genes.

**Comment by sdws1983** [comment]
Thank you for your response. What do the dark and light colors represent in the ATGC score curve?

**Comment by PelFritz** [comment]
The light colors indicate the scores average for genes that were correctly predicted as lowly expressed, while thick (dark)
 colors means these genes were correctly predicted as highly expressed
